const pairs=[['Cappuccino','Latte'],['Purse','Wallet'],['Sofa','Armchair'],['Lake','Pond']];
const state={players:['Alex','Mina','Sam'],view:'home',phase:'home',turn:0,word:'Cappuccino',clues:[],votes:{}};
const app=document.querySelector('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shell(html){app.innerHTML=html;window.scrollTo(0,0)}
function home(){state.phase='home';shell(`<section class="hero"><div class="eyebrow">A party game of careful clues</div><h1>Two words.<br><span>One room.</span></h1><p>Most of you will see one word. A few will see a close cousin. Give clues, read the room, and find the difference — without giving your word away.</p><div class="actions"><button class="primary" data-view="setup">Pass &amp; Play <span aria-hidden="true">→</span></button><button class="secondary" data-view="online">Play Online <span aria-hidden="true">↗</span></button></div></section><section class="pair-card"><header><span>Tonight's example</span><span>Food &amp; drink</span></header><div class="pair"><span>Cappuccino</span><i>×</i><span>Latte</span></div><small>Related, but never quite the same.</small></section><div class="grid"><article class="panel"><h3>Same card. Different word.</h3><p>Everyone gets the same quiet reveal. No colors, labels, or tells — only the clues give the game away.</p><button class="text-button" data-view="how">See how it works →</button></article><article class="panel"><h3>Made for the table.</h3><p>Pass one phone around for a quick local game, or create a private room when everyone has their own screen.</p><button class="text-button" data-view="privacy">Read the privacy note →</button></article></div>`)}
function setup(){shell(`<section class="page"><div class="eyebrow">Pass &amp; Play</div><h1>Set up your table</h1><p>Add everyone playing. The device will hand out private words one at a time, then guide the table through clues and voting.</p><div class="panel"><div class="section-label">Players <span id="count">(${state.players.length}/24)</span></div><div class="field"><input class="input" id="name" placeholder="Player name" maxlength="24"><button class="primary" id="add">Add</button></div><div class="names" id="names">${state.players.map((n,i)=>`<span class="chip">${esc(n)} <button aria-label="Remove ${esc(n)}" data-remove="${i}">×</button></span>`).join('')}</div><div class="section-label">Difficulty</div><div class="options"><button class="option selected">Easy</button><button class="option">Medium</button></div><div class="section-label">Minority count</div><div class="options"><button class="option selected">1 player</button><button class="option">2 players</button></div><div class="notice" style="margin-top:22px">A local game is private by handoff, not by encryption. Refreshing during play restarts the game.</div><button class="primary" id="start" style="width:100%;margin-top:18px" ${state.players.length<3?'disabled':''}>Start game · ${state.players.length} players</button></div></section>`)}
function reveal(){const player=state.players[state.turn];shell(`<section class="game-stage"><div class="progress">Private handoff · ${state.turn+1} of ${state.players.length}</div><div class="stage-card"><div><p>Pass the device to</p><h2>${esc(player)}</h2><p>Only ${esc(player)} should look at the next screen.</p></div></div><button class="primary" id="show-word">Reveal my word</button><p style="color:var(--muted);font-size:13px;margin-top:18px">Your word disappears when you hide it.</p></section>`)}
function word(){shell(`<section class="game-stage"><div class="progress">Private word · ${state.turn+1} of ${state.players.length}</div><div class="stage-card"><div><p>Your word</p><div class="reveal-word">${esc(state.word)}</div><p>Describe your word without saying it.</p></div></div><button class="primary" id="hide-word">Hide and pass</button></section>`)}
function clues(){const current=state.players[state.turn%state.players.length];shell(`<section class="page"><div class="progress">Clues · cycle 1</div><h1>${esc(current)}'s clue</h1><p>Say one short clue out loud. Keep it specific enough to be useful, but not so specific that it gives your word away.</p><div class="panel"><div class="notice">No typing needed in Pass &amp; Play. The table listens, then taps next.</div><button class="primary" id="next-clue" style="width:100%;margin-top:18px">Next player →</button></div><div class="clue-list">${state.clues.length?state.clues.map(c=>`<div class="clue"><b>${esc(c.player)}</b><span>${esc(c.text)}</span></div>`).join(''):'<p style="color:var(--muted)">Clues will appear here as the table moves.</p>'}</div></section>`)}
function discussion(){shell(`<section class="page"><div class="progress">Discussion · 90 seconds</div><h1>What feels different?</h1><p>Talk it through. Which clues sounded just a little off? When the table is ready, vote privately.</p><div class="panel"><div class="notice">Keep the word cards hidden. A tied vote leads to a short runoff.</div><button class="primary" id="vote" style="width:100%;margin-top:18px">Start private vote</button></div></section>`)}
function voting(){shell(`<section class="page"><div class="progress">Private vote · ${state.players.length} votes</div><h1>Choose one player</h1><p>Pass the device. Each person selects one other player or abstains. Choices stay hidden until voting ends.</p><div class="choice-list">${state.players.map((n,i)=>`<button class="choice" data-vote="${i}"><span>${esc(n)}</span><span aria-hidden="true">○</span></button>`).join('')}<button class="choice" data-vote="abstain"><span>Abstain</span><span aria-hidden="true">—</span></button></div><button class="primary" id="finish-vote" style="width:100%" disabled>Confirm vote</button></section>`)}
function results(){shell(`<section class="page"><div class="eyebrow">Game complete</div><h1>The table has spoken.</h1><p>Both words are revealed now. The winning team earns one point each, including players who were eliminated.</p><div class="panel"><div class="pair"><span>Cappuccino</span><i>×</i><span>Latte</span></div><div class="notice">The group with the most surviving players wins this round.</div><button class="primary" data-view="setup" style="width:100%;margin-top:18px">Play again</button></div><button class="text-button" data-view="home" style="display:block;margin:22px auto">Back to home</button></section>`)}
function how(){shell(`<section class="page"><div class="eyebrow">How to play</div><h1>Listen between the words.</h1><p>Every game uses a pair of related words. Everyone knows the pair is close, but nobody knows which side is more common.</p><div class="steps"><div class="step"><b>1</b><p><strong>Reveal privately.</strong><br>Pass the device and tap to see your neutral word card.</p></div><div class="step"><b>2</b><p><strong>Give a clue.</strong><br>Describe your word without saying it or an obvious variation.</p></div><div class="step"><b>3</b><p><strong>Discuss and vote.</strong><br>Find the clues that do not quite fit. Ties go to a runoff.</p></div><div class="step"><b>4</b><p><strong>See the result.</strong><br>Only after the final resolution are the two words and groups shown.</p></div></div><button class="primary" data-view="setup">Set up a local game</button></section>`)}
function online(){shell(`<section class="page"><div class="eyebrow">Play online</div><h1>Private rooms, coming next.</h1><p>Online play needs a small persistent game service so rooms, timers, and private words stay authoritative. The local mode is ready to play on this device now.</p><div class="panel"><div class="notice">No fake room or fake multiplayer here — this button is intentionally a clear boundary.</div><button class="secondary" data-view="home" style="width:100%;margin-top:18px">Back to home</button></div></section>`)}
function privacy(){shell(`<section class="page"><div class="eyebrow">Privacy</div><h1>Small by design.</h1><p>This prototype keeps local setup and scores in the current page only. It does not create accounts, send words to a server, or use analytics. A shared device cannot protect secrets from someone using developer tools or taking a screenshot.</p><button class="primary" data-view="home">Back to home</button></section>`)}
function render(){({home,setup,reveal,word,clues,discussion,voting,results,how,online,privacy}[state.view]||home)()}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]')?.dataset.view;if(v){state.view=v;render();return}if(e.target.id==='add'){const input=document.querySelector('#name');const n=input.value.trim();if(n&&state.players.length<24&&!state.players.some(p=>p.toLowerCase()===n.toLowerCase())){state.players.push(n);setup()}return}if(e.target.dataset.remove){state.players.splice(+e.target.dataset.remove,1);setup();return}if(e.target.id==='start'){state.turn=0;state.view='reveal';render();return}if(e.target.id==='show-word'){state.view='word';render();return}if(e.target.id==='hide-word'){state.turn++;if(state.turn<state.players.length){state.view='reveal'}else{state.turn=0;state.view='clues'}render();return}if(e.target.id==='next-clue'){state.clues.push({player:state.players[state.turn%state.players.length],text:['Warm foam','A quiet morning','You can hold it'][state.clues.length%3]});state.turn++;if(state.turn<state.players.length){clues()}else{state.view='discussion';render()}return}if(e.target.id==='vote'){state.view='voting';render();return}if(e.target.dataset.vote){document.querySelectorAll('[data-vote]').forEach(b=>b.classList.remove('selected'));e.target.classList.add('selected');document.querySelector('#finish-vote').disabled=false;return}if(e.target.id==='finish-vote'){state.view='results';render()}});
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(v){state.view=v;render()}});render();
