import type { PairSeed } from './schema.ts'

/**
 * Everyday categories. Each pair is two genuinely related things that a player
 * can describe without naming, and that a listener could plausibly confuse.
 *
 * Editorial rules applied to every row:
 * - Not synonyms. There is always a describable difference, recorded in the note.
 * - Neither side is consistently the more famous or more specific of the two,
 *   so the randomized orientation cannot be reverse-engineered from the words.
 * - `easy` pairs stay within general knowledge; anything needing specialist
 *   familiarity is marked `hard`.
 *
 * These are editorial judgements. They have not been playtested.
 */

export const FOOD: PairSeed[] = [
  ['Pizza', 'Calzone', 'easy', 'A calzone is folded and sealed; pizza stays open-faced.'],
  ['Burger', 'Sandwich', 'easy', 'A burger centres on a patty in a bun; a sandwich is broader.'],
  ['Pancake', 'Crepe', 'easy', 'Crepes are thin and unleavened; pancakes are thick and raised.'],
  ['Waffle', 'Pancake', 'easy', 'Waffles cook in a gridded iron; pancakes on a flat griddle.'],
  ['Doughnut', 'Bagel', 'easy', 'Both are rings, but doughnuts are sweet and fried, bagels boiled then baked.'],
  ['Croissant', 'Brioche', 'medium', 'A croissant is laminated and flaky; brioche is a soft enriched loaf.'],
  ['Muffin', 'Cupcake', 'easy', 'Cupcakes are frosted dessert; muffins are plainer and often breakfast.'],
  ['Scone', 'Biscuit', 'medium', 'A scone is sweeter and eaten with jam; a biscuit is savoury and flaky.'],
  ['Cookie', 'Cracker', 'easy', 'Cookies are sweet; crackers are dry and savoury.'],
  ['Cake', 'Pie', 'easy', 'Cake is a baked batter; pie is a filling inside pastry.'],
  ['Tart', 'Pie', 'medium', 'Tarts are shallow and open-topped; pies are deeper and often lidded.'],
  ['Pudding', 'Custard', 'medium', 'Custard is egg-thickened and pourable; pudding is set and spoonable.'],
  ['Ice cream', 'Gelato', 'medium', 'Gelato has less fat and less churned air, and is served warmer.'],
  ['Sorbet', 'Sherbet', 'hard', 'Sherbet contains a little dairy; sorbet none at all.'],
  ['Yogurt', 'Kefir', 'hard', 'Kefir is drinkable and yeast-fermented; yogurt is spoonable.'],
  ['Cheese', 'Butter', 'easy', 'Cheese is curdled and aged; butter is churned fat.'],
  ['Cheddar', 'Mozzarella', 'easy', 'Cheddar is sharp and firm; mozzarella mild and stretchy.'],
  ['Brie', 'Camembert', 'hard', 'Camembert is earthier and sold in smaller rounds.'],
  ['Omelette', 'Frittata', 'medium', 'A frittata finishes in the oven and is served open; an omelette is folded.'],
  ['Quiche', 'Frittata', 'medium', 'Quiche sits in a pastry crust; a frittata has none.'],
  ['Pasta', 'Noodles', 'easy', 'Pasta is Italian and usually wheat; noodles span many cuisines and flours.'],
  ['Spaghetti', 'Linguine', 'medium', 'Linguine is flattened; spaghetti is round.'],
  ['Macaroni', 'Penne', 'medium', 'Penne is straight with angled ends; macaroni is curved and smaller.'],
  ['Lasagna', 'Ravioli', 'easy', 'Lasagna is layered sheets; ravioli is filled parcels.'],
  ['Dumpling', 'Ravioli', 'medium', 'Ravioli is specifically Italian pasta; dumpling is the broader idea.'],
  ['Sushi', 'Sashimi', 'medium', 'Sashimi is sliced fish alone; sushi includes seasoned rice.'],
  ['Rice', 'Quinoa', 'easy', 'Quinoa is a seed with a nuttier bite; rice is a grain.'],
  ['Risotto', 'Paella', 'medium', 'Risotto is stirred creamy Italian rice; paella is Spanish and left to crust.'],
  ['Soup', 'Stew', 'easy', 'Stew is thicker with more solids; soup is mostly liquid.'],
  ['Chowder', 'Bisque', 'hard', 'Bisque is smooth and strained; chowder is chunky.'],
  ['Salad', 'Slaw', 'easy', 'Slaw is shredded cabbage in dressing; salad is broader and usually leafy.'],
  ['Sandwich', 'Wrap', 'easy', 'Wraps use a rolled flatbread; sandwiches use sliced bread.'],
  ['Taco', 'Burrito', 'easy', 'Burritos are fully wrapped and sealed; tacos stay open.'],
  ['Quesadilla', 'Taco', 'easy', 'A quesadilla is griddled and cheese-filled; a taco is assembled at the end.'],
  ['Tortilla', 'Pita', 'medium', 'Pita puffs into a pocket; a tortilla stays flat.'],
  ['Baguette', 'Ciabatta', 'medium', 'Ciabatta is flatter with an open airy crumb; a baguette is long and crisp.'],
  ['Jam', 'Jelly', 'medium', 'Jelly is strained clear juice; jam keeps the fruit pulp.'],
  ['Honey', 'Syrup', 'easy', 'Honey is made by bees; syrup is boiled from sap or sugar.'],
  ['Peanut butter', 'Almond butter', 'medium', 'A different nut, milder and less sweet.'],
  ['Chocolate', 'Fudge', 'easy', 'Fudge is a soft cooked sugar confection; chocolate is set cocoa.'],
  ['Candy', 'Gum', 'easy', 'Gum is chewed and not swallowed; candy is eaten.'],
  ['Lollipop', 'Popsicle', 'easy', 'Popsicles are frozen; lollipops are hard sugar at room temperature.'],
  ['Cereal', 'Granola', 'easy', 'Granola is baked in clusters with oil and sweetener; cereal is lighter.'],
  ['Oatmeal', 'Grits', 'medium', 'Grits are ground corn; oatmeal is rolled oats.'],
  ['Bacon', 'Ham', 'easy', 'Bacon is cured belly cooked crisp; ham is cured leg served in slices.'],
  ['Sausage', 'Hot dog', 'easy', 'Hot dogs are emulsified and pre-cooked; sausages are coarser and cooked fresh.'],
  ['Steak', 'Roast', 'easy', 'Steak is a quick-seared cut; a roast is a large joint cooked slowly.'],
  ['Meatball', 'Meatloaf', 'easy', 'Meatloaf is one baked loaf; meatballs are portioned and rolled.'],
  ['Hash brown', 'Tater tot', 'medium', 'Tots are shaped cylinders; hash browns are loose shredded potato.'],
  ['Mashed potato', 'Baked potato', 'easy', 'A baked potato keeps its skin and shape; mashed is whipped.'],
]

export const DRINKS: PairSeed[] = [
  ['Cappuccino', 'Latte', 'easy', 'A cappuccino has more foam and less steamed milk.'],
  ['Espresso', 'Americano', 'easy', 'An americano is espresso let down with hot water.'],
  ['Macchiato', 'Cortado', 'hard', 'A cortado is equal parts milk; a macchiato only a spot of foam.'],
  ['Flat white', 'Latte', 'hard', 'A flat white is smaller with thinner microfoam.'],
  ['Mocha', 'Hot chocolate', 'easy', 'A mocha contains espresso; hot chocolate does not.'],
  ['Tea', 'Coffee', 'easy', 'A different plant entirely; tea is steeped leaves.'],
  ['Green tea', 'Black tea', 'easy', 'Black tea is fully oxidised; green tea is not.'],
  ['Chai', 'Matcha', 'medium', 'Matcha is powdered green tea whisked in; chai is spiced black tea with milk.'],
  ['Oolong', 'Pu-erh', 'hard', 'Pu-erh is aged and fermented; oolong only partially oxidised.'],
  ['Herbal tea', 'Iced tea', 'medium', 'Herbal tea contains no tea leaf; iced tea is chilled true tea.'],
  ['Lemonade', 'Limeade', 'easy', 'A different citrus fruit.'],
  ['Orange juice', 'Apple juice', 'easy', 'Different fruit, colour and acidity.'],
  ['Smoothie', 'Milkshake', 'easy', 'Milkshakes are ice-cream based; smoothies are fruit and yogurt.'],
  ['Soda', 'Sparkling water', 'easy', 'Soda is sweetened and flavoured; sparkling water is plain carbonated.'],
  ['Cola', 'Root beer', 'easy', 'Root beer is sassafras-flavoured; cola is citrus and caramel.'],
  ['Ginger ale', 'Ginger beer', 'medium', 'Ginger beer is brewed, spicier and cloudier.'],
  ['Tonic water', 'Club soda', 'medium', 'Tonic carries quinine and sugar; club soda only added minerals.'],
  ['Beer', 'Cider', 'easy', 'Cider is fermented apples; beer is fermented grain.'],
  ['Lager', 'Ale', 'medium', 'Lager ferments cold and slow; ale warm and fast.'],
  ['Stout', 'Porter', 'hard', 'Stout is typically darker and more heavily roasted.'],
  ['Wine', 'Champagne', 'easy', 'Champagne is sparkling and from one region.'],
  ['Red wine', 'White wine', 'easy', 'Grape skins are left in for red.'],
  ['Prosecco', 'Champagne', 'medium', 'Different countries and second-fermentation methods.'],
  ['Whiskey', 'Bourbon', 'medium', 'Bourbon is a corn-based American whiskey aged in new charred oak.'],
  ['Rum', 'Vodka', 'easy', 'Rum comes from sugarcane; vodka from neutral grain or potato.'],
  ['Gin', 'Vodka', 'medium', 'Gin is a neutral spirit flavoured with juniper.'],
  ['Tequila', 'Mezcal', 'medium', 'Mezcal is smokier and made from many agave varieties.'],
  ['Brandy', 'Cognac', 'medium', 'Cognac is brandy from one French region.'],
  ['Cocktail', 'Mocktail', 'easy', 'Mocktails contain no alcohol.'],
  ['Margarita', 'Daiquiri', 'medium', 'A margarita uses tequila; a daiquiri rum.'],
  ['Martini', 'Manhattan', 'medium', 'A manhattan uses whiskey and sweet vermouth; a martini gin and dry.'],
  ['Mojito', 'Caipirinha', 'hard', 'A caipirinha uses cachaca and no mint.'],
  ['Sangria', 'Punch', 'medium', 'Sangria is specifically wine-based with fruit.'],
  ['Milk', 'Cream', 'easy', 'Cream is the higher-fat layer.'],
  ['Buttermilk', 'Milk', 'medium', 'Buttermilk is cultured and tangy.'],
  ['Almond milk', 'Oat milk', 'easy', 'A different plant base and texture.'],
  ['Hot cocoa', 'Malted milk', 'hard', 'Malted milk uses barley malt powder rather than cocoa alone.'],
  ['Energy drink', 'Sports drink', 'easy', 'Energy drinks add caffeine; sports drinks replace electrolytes.'],
  ['Kombucha', 'Kefir', 'hard', 'Kombucha is fermented tea; kefir is fermented milk.'],
  ['Iced coffee', 'Cold brew', 'medium', 'Cold brew steeps cold for hours; iced coffee is brewed hot then chilled.'],
  ['Frappe', 'Affogato', 'medium', 'An affogato is espresso poured over ice cream; a frappe is blended and iced.'],
  ['Milkshake', 'Float', 'medium', 'A float is soda with ice cream on top, not blended together.'],
  ['Still water', 'Mineral water', 'medium', 'Mineral water carries dissolved minerals from its source.'],
  ['Coconut water', 'Coconut milk', 'easy', 'Water is the thin liquid inside; milk is pressed from the flesh.'],
  ['Nectar', 'Juice', 'medium', 'Nectar is diluted sweetened pulp; juice is pressed and undiluted.'],
  ['Slushie', 'Smoothie', 'easy', 'Slushies are ice and syrup; smoothies are blended fruit.'],
  ['Eggnog', 'Horchata', 'hard', 'Horchata is rice or nut based with cinnamon; eggnog is dairy and egg.'],
  ['Sake', 'Soju', 'hard', 'Sake is brewed rice wine; soju is distilled and stronger.'],
  ['Vermouth', 'Sherry', 'hard', 'Vermouth is aromatised with botanicals; sherry is fortified.'],
  ['Hot toddy', 'Mulled wine', 'hard', 'Mulled wine is spiced heated wine; a toddy is spirits, honey and hot water.'],
]

export const CLOTHING: PairSeed[] = [
  ['Purse', 'Wallet', 'easy', 'A wallet folds flat for cards; a purse is a carried bag.'],
  ['Backpack', 'Satchel', 'easy', 'A backpack has two shoulder straps; a satchel one across the body.'],
  ['Suitcase', 'Duffel bag', 'easy', 'A suitcase is rigid and wheeled; a duffel is soft and carried.'],
  ['Scarf', 'Shawl', 'easy', 'A shawl drapes over the shoulders; a scarf wraps the neck.'],
  ['Hat', 'Cap', 'easy', 'A cap has a front brim only; a hat usually a full one.'],
  ['Beanie', 'Beret', 'medium', 'A beret is flat and stiffened wool; a beanie is stretchy and snug.'],
  ['Gloves', 'Mittens', 'easy', 'Mittens keep the fingers together; gloves separate them.'],
  ['Socks', 'Tights', 'easy', 'Tights continue up the leg as one garment.'],
  ['Shoes', 'Sandals', 'easy', 'Sandals are open-topped; shoes enclose the foot.'],
  ['Sneakers', 'Loafers', 'easy', 'Loafers are slip-on and formal; sneakers laced and athletic.'],
  ['Boots', 'Sneakers', 'easy', 'Boots rise above the ankle.'],
  ['Heels', 'Flats', 'easy', 'Heels raise the back of the foot; flats keep it level.'],
  ['Slippers', 'Flip-flops', 'easy', 'Slippers are soft and indoor; flip-flops are outdoor and toe-post.'],
  ['Shirt', 'Blouse', 'easy', 'A blouse is looser and traditionally cut for women.'],
  ['T-shirt', 'Polo shirt', 'easy', 'A polo has a collar and a short button placket.'],
  ['Sweater', 'Cardigan', 'easy', 'A cardigan opens down the front; a sweater pulls over.'],
  ['Hoodie', 'Sweatshirt', 'easy', 'A hoodie adds a hood and usually a front pocket.'],
  ['Jacket', 'Coat', 'easy', 'A coat is longer and warmer.'],
  ['Blazer', 'Suit jacket', 'medium', 'A blazer is worn alone; a suit jacket matches its trousers.'],
  ['Raincoat', 'Windbreaker', 'medium', 'A raincoat is waterproof; a windbreaker only blocks wind.'],
  ['Vest', 'Waistcoat', 'medium', 'A waistcoat is tailored formalwear; a vest is broader and often padded.'],
  ['Jeans', 'Chinos', 'easy', 'Chinos are smooth cotton twill; jeans are denim.'],
  ['Trousers', 'Leggings', 'easy', 'Leggings are stretch-fitted to the leg.'],
  ['Shorts', 'Skirt', 'easy', 'Shorts have separate legs; a skirt is a single panel.'],
  ['Dress', 'Gown', 'easy', 'A gown is longer and formal.'],
  ['Jumpsuit', 'Overalls', 'medium', 'Overalls have a bib and straps over a separate top.'],
  ['Pyjamas', 'Robe', 'easy', 'A robe wraps and ties over other clothes.'],
  ['Swimsuit', 'Wetsuit', 'easy', 'A wetsuit is thick neoprene for warmth.'],
  ['Belt', 'Suspenders', 'easy', 'Suspenders hang from the shoulders; a belt cinches the waist.'],
  ['Tie', 'Bow tie', 'easy', 'A bow tie is short and tied at the collar.'],
  ['Necklace', 'Choker', 'easy', 'A choker sits tight at the throat.'],
  ['Bracelet', 'Bangle', 'medium', 'A bangle is rigid; a bracelet flexible or chained.'],
  ['Ring', 'Earring', 'easy', 'Different part of the body entirely.'],
  ['Watch', 'Bracelet', 'easy', 'A watch tells the time.'],
  ['Sunglasses', 'Glasses', 'easy', 'Sunglasses are tinted for glare, not correction.'],
  ['Umbrella', 'Parasol', 'medium', 'A parasol shades from sun and is not waterproof.'],
  ['Apron', 'Smock', 'medium', 'A smock covers the whole torso and sleeves; an apron only the front.'],
  ['Uniform', 'Costume', 'easy', 'A costume is worn to portray something; a uniform to identify a role.'],
  ['Hoodie', 'Poncho', 'medium', 'A poncho is a single sheet with a head opening and no sleeves.'],
  ['Cufflinks', 'Buttons', 'medium', 'Cufflinks are removable fasteners for a French cuff.'],
  ['Zipper', 'Velcro', 'easy', 'Velcro grips by hooks and loops; a zipper by interlocking teeth.'],
  ['Denim', 'Corduroy', 'medium', 'Corduroy has raised vertical ridges.'],
  ['Wool', 'Cotton', 'easy', 'Wool comes from animals; cotton from a plant.'],
  ['Silk', 'Satin', 'medium', 'Silk is a fibre; satin is a weave that can use several fibres.'],
  ['Leather', 'Suede', 'medium', 'Suede is the napped underside, soft rather than smooth.'],
  ['Linen', 'Cotton', 'medium', 'Linen comes from flax and creases more sharply.'],
  ['Cape', 'Cloak', 'hard', 'A cloak is longer and fully encloses; a cape stops at the shoulders.'],
  ['Sari', 'Kimono', 'medium', 'A sari is draped unstitched cloth; a kimono a stitched wrapped robe.'],
  ['Turban', 'Headscarf', 'medium', 'A turban is wound into shape; a headscarf is draped and tied.'],
  ['Cardigan', 'Shrug', 'hard', 'A shrug covers only the arms and upper back.'],
]

export const HOUSEHOLD: PairSeed[] = [
  ['Sofa', 'Armchair', 'easy', 'An armchair seats one; a sofa several.'],
  ['Stool', 'Chair', 'easy', 'A chair has a back; a stool does not.'],
  ['Bench', 'Sofa', 'easy', 'A bench is hard-topped and usually backless.'],
  ['Table', 'Desk', 'easy', 'A desk is built for working, usually with drawers.'],
  ['Shelf', 'Cabinet', 'easy', 'A cabinet has doors; a shelf is open.'],
  ['Wardrobe', 'Dresser', 'easy', 'A wardrobe hangs clothes; a dresser stores them folded in drawers.'],
  ['Bed', 'Cot', 'easy', 'A cot is small, portable and often for a child.'],
  ['Mattress', 'Futon', 'medium', 'A futon folds and doubles as seating.'],
  ['Pillow', 'Cushion', 'easy', 'A pillow supports the head in bed; a cushion pads a seat.'],
  ['Blanket', 'Quilt', 'easy', 'A quilt is stitched in layers with padding between.'],
  ['Duvet', 'Comforter', 'hard', 'A duvet needs a removable cover; a comforter is finished on the outside.'],
  ['Curtain', 'Blind', 'easy', 'Blinds are slatted or rolled; curtains are hung fabric.'],
  ['Rug', 'Carpet', 'easy', 'Carpet covers the whole floor and is fixed down.'],
  ['Mirror', 'Picture frame', 'easy', 'A mirror reflects rather than displays.'],
  ['Lamp', 'Chandelier', 'easy', 'A chandelier hangs from the ceiling with several branches.'],
  ['Candle', 'Lantern', 'easy', 'A lantern is a case that carries and shields a light.'],
  ['Broom', 'Mop', 'easy', 'A mop is used wet; a broom dry.'],
  ['Vacuum', 'Broom', 'easy', 'A vacuum suctions with a motor.'],
  ['Bucket', 'Basin', 'easy', 'A basin is wide and shallow; a bucket deep with a handle.'],
  ['Sponge', 'Dishcloth', 'easy', 'A sponge is thick and absorbent; a dishcloth is woven and flat.'],
  ['Towel', 'Napkin', 'easy', 'A napkin is small and used at the table.'],
  ['Soap', 'Detergent', 'easy', 'Detergent is synthetic and made for laundry or dishes.'],
  ['Kettle', 'Teapot', 'easy', 'A kettle heats the water; a teapot steeps the leaves.'],
  ['Pot', 'Pan', 'easy', 'A pot is deep for liquids; a pan shallow for frying.'],
  ['Skillet', 'Wok', 'medium', 'A wok is deep and round-bottomed for tossing.'],
  ['Saucepan', 'Stockpot', 'medium', 'A stockpot is far taller for large batches.'],
  ['Oven', 'Microwave', 'easy', 'A microwave heats with radiation rather than surrounding heat.'],
  ['Stove', 'Grill', 'easy', 'A grill cooks over open heat from below or above.'],
  ['Toaster', 'Toaster oven', 'medium', 'A toaster oven has a door and shelf and can bake.'],
  ['Blender', 'Food processor', 'medium', 'A processor chops and slices; a blender liquefies.'],
  ['Mixer', 'Whisk', 'easy', 'A whisk is handheld and unpowered.'],
  ['Fridge', 'Freezer', 'easy', 'A freezer holds below freezing; a fridge merely cold.'],
  ['Dishwasher', 'Washing machine', 'easy', 'One washes dishes, the other clothes.'],
  ['Dryer', 'Clothesline', 'easy', 'A clothesline dries in the air without power.'],
  ['Iron', 'Steamer', 'medium', 'A steamer relaxes creases hanging; an iron presses them flat.'],
  ['Plate', 'Bowl', 'easy', 'A bowl has deep sides for liquids.'],
  ['Mug', 'Cup', 'easy', 'A mug is taller with a sturdy handle and no saucer.'],
  ['Glass', 'Tumbler', 'medium', 'A tumbler is flat-bottomed and stemless.'],
  ['Fork', 'Spoon', 'easy', 'A fork spears with tines; a spoon scoops.'],
  ['Knife', 'Peeler', 'easy', 'A peeler removes only a thin skin.'],
  ['Chopsticks', 'Tongs', 'easy', 'Tongs are hinged and gripped in one hand.'],
  ['Spatula', 'Ladle', 'easy', 'A ladle is a deep bowl for serving liquid.'],
  ['Colander', 'Sieve', 'medium', 'A sieve has fine mesh for flour; a colander large holes for draining.'],
  ['Jar', 'Bottle', 'easy', 'A bottle has a narrow neck; a jar a wide mouth.'],
  ['Tray', 'Platter', 'medium', 'A tray carries; a platter serves at the table.'],
  ['Bin', 'Basket', 'easy', 'A bin is for waste; a basket for carrying or storing.'],
  ['Hanger', 'Hook', 'easy', 'A hanger holds a garment in shape on a rail.'],
  ['Doormat', 'Rug', 'easy', 'A doormat is coarse and sits at an entrance to scrape shoes.'],
  ['Clock', 'Timer', 'easy', 'A timer counts down a set interval.'],
  ['Fan', 'Air conditioner', 'easy', 'An air conditioner cools the air; a fan only moves it.'],
]

export const ANIMALS: PairSeed[] = [
  ['Crocodile', 'Alligator', 'easy', 'An alligator has a broader, rounder snout.'],
  ['Frog', 'Toad', 'easy', 'Toads have drier, warty skin and shorter legs.'],
  ['Turtle', 'Tortoise', 'easy', 'A tortoise lives on land; a turtle in water.'],
  ['Rabbit', 'Hare', 'easy', 'Hares are larger, faster and born fully furred.'],
  ['Mouse', 'Rat', 'easy', 'Rats are larger with thicker tails.'],
  ['Squirrel', 'Chipmunk', 'easy', 'Chipmunks are smaller with striped backs and cheek pouches.'],
  ['Hamster', 'Guinea pig', 'easy', 'Guinea pigs are larger with almost no tail.'],
  ['Ferret', 'Weasel', 'medium', 'A ferret is the domesticated one.'],
  ['Otter', 'Beaver', 'easy', 'Beavers have flat paddle tails and fell trees.'],
  ['Seal', 'Sea lion', 'medium', 'Sea lions have visible ear flaps and walk on their flippers.'],
  ['Dolphin', 'Porpoise', 'medium', 'Porpoises are smaller with blunt snouts and spade-shaped teeth.'],
  ['Whale', 'Shark', 'easy', 'A whale is a mammal that breathes air.'],
  ['Octopus', 'Squid', 'easy', 'A squid has eight arms plus two long tentacles and a firmer body.'],
  ['Crab', 'Lobster', 'easy', 'A lobster has a long tail and body; a crab a wide flat shell.'],
  ['Shrimp', 'Prawn', 'hard', 'They differ in gill structure and body segment overlap.'],
  ['Butterfly', 'Moth', 'easy', 'Moths fly at night and rest with wings spread flat.'],
  ['Bee', 'Wasp', 'easy', 'Wasps are smoother and narrow-waisted; bees hairy and rounder.'],
  ['Ant', 'Termite', 'medium', 'Termites are pale with straight antennae and eat wood.'],
  ['Spider', 'Scorpion', 'easy', 'A scorpion has pincers and a stinging tail.'],
  ['Grasshopper', 'Cricket', 'medium', 'Crickets have long antennae and chirp at night.'],
  ['Dragonfly', 'Damselfly', 'hard', 'Damselflies fold their wings along the body at rest.'],
  ['Crow', 'Raven', 'medium', 'Ravens are larger with wedge-shaped tails and deeper calls.'],
  ['Eagle', 'Hawk', 'easy', 'Eagles are considerably larger with heavier beaks.'],
  ['Owl', 'Falcon', 'easy', 'Owls hunt at night with silent flight.'],
  ['Duck', 'Goose', 'easy', 'Geese are larger with longer necks.'],
  ['Swan', 'Goose', 'easy', 'Swans are larger with much longer curved necks.'],
  ['Chicken', 'Turkey', 'easy', 'Turkeys are much larger with a wattled bare head.'],
  ['Pigeon', 'Dove', 'medium', 'Doves are generally smaller and slimmer; the split is not scientific.'],
  ['Sparrow', 'Finch', 'medium', 'Finches have conical seed-cracking bills and brighter colouring.'],
  ['Penguin', 'Puffin', 'easy', 'Puffins can fly and have bright triangular bills.'],
  ['Ostrich', 'Emu', 'medium', 'Ostriches are taller with two toes; emus are Australian with three.'],
  ['Flamingo', 'Heron', 'easy', 'Herons are grey and spear fish; flamingos filter-feed and are pink.'],
  ['Peacock', 'Pheasant', 'medium', 'Peacocks fan an enormous eyed tail.'],
  ['Parrot', 'Parakeet', 'medium', 'Parakeets are small and long-tailed.'],
  ['Leopard', 'Cheetah', 'easy', 'Cheetahs are slimmer with solid spots and black tear lines.'],
  ['Jaguar', 'Leopard', 'medium', 'Jaguars are stockier with rosettes that have centre dots.'],
  ['Lion', 'Tiger', 'easy', 'Tigers are striped and solitary; lions maned and social.'],
  ['Wolf', 'Coyote', 'easy', 'Coyotes are smaller and narrower-faced.'],
  ['Fox', 'Coyote', 'medium', 'Foxes are much smaller with bushier tails.'],
  ['Donkey', 'Mule', 'medium', 'A mule is the hybrid offspring of a donkey and a horse.'],
  ['Horse', 'Pony', 'easy', 'A pony is a short breed, not simply a young horse.'],
  ['Camel', 'Llama', 'easy', 'Llamas are smaller, South American and humpless.'],
  ['Alpaca', 'Llama', 'medium', 'Alpacas are smaller with finer fleece and blunt faces.'],
  ['Goat', 'Sheep', 'easy', 'Sheep grow wool; goats have hair and upright tails.'],
  ['Deer', 'Antelope', 'medium', 'Deer shed branched antlers; antelope keep permanent horns.'],
  ['Moose', 'Elk', 'medium', 'Moose are larger with broad flat palmate antlers.'],
  ['Bison', 'Buffalo', 'medium', 'True buffalo are African and Asian; bison are American and humped.'],
  ['Rhinoceros', 'Hippopotamus', 'easy', 'Hippos are aquatic and hornless.'],
  ['Chimpanzee', 'Gorilla', 'easy', 'Gorillas are far larger with a pronounced brow and crest.'],
  ['Monkey', 'Lemur', 'medium', 'Lemurs are Madagascan primates with long ringed tails and fox-like faces.'],
]
