import type { PairSeed } from './schema.ts'

/**
 * World and activity categories. Same editorial rules as `pairs-everyday.ts`:
 * related but distinguishable, neither side reliably the more obvious one, and
 * a note recording the actual difference.
 */

export const TRANSPORT: PairSeed[] = [
  ['Bicycle', 'Motorcycle', 'easy', 'A motorcycle has an engine; a bicycle is pedalled.'],
  ['Scooter', 'Motorcycle', 'easy', 'A scooter has a step-through frame and smaller wheels.'],
  ['Skateboard', 'Scooter', 'easy', 'A scooter has a handlebar to hold.'],
  ['Rollerblades', 'Roller skates', 'medium', 'Rollerblades have a single line of wheels; skates two pairs.'],
  ['Car', 'Van', 'easy', 'A van is boxier and built for cargo or many seats.'],
  ['Truck', 'Lorry', 'medium', 'The same vehicle under British and American names, sized differently in use.'],
  ['Bus', 'Coach', 'medium', 'A coach is built for long distance with luggage holds.'],
  ['Tram', 'Train', 'easy', 'A tram runs on street rails within a city.'],
  ['Subway', 'Monorail', 'easy', 'A monorail runs elevated on a single beam.'],
  ['Ferry', 'Cruise ship', 'easy', 'A ferry is a short crossing; a cruise ship is the holiday itself.'],
  ['Boat', 'Ship', 'easy', 'A ship is large enough to carry boats.'],
  ['Canoe', 'Kayak', 'easy', 'A kayak is enclosed and uses a double-bladed paddle.'],
  ['Raft', 'Dinghy', 'medium', 'A dinghy is a small rigid boat; a raft a flat buoyant platform.'],
  ['Yacht', 'Sailboat', 'medium', 'A yacht is larger and often motorised for leisure.'],
  ['Submarine', 'Torpedo', 'medium', 'A torpedo is a weapon; a submarine carries people.'],
  ['Helicopter', 'Airplane', 'easy', 'A helicopter lifts with rotors and can hover.'],
  ['Jet', 'Propeller plane', 'easy', 'A jet burns thrust; a propeller pulls with blades.'],
  ['Glider', 'Paraglider', 'medium', 'A paraglider uses a fabric wing and launches on foot.'],
  ['Hot air balloon', 'Blimp', 'medium', 'A blimp is powered and steerable; a balloon drifts with the wind.'],
  ['Parachute', 'Hang glider', 'easy', 'A hang glider has a rigid frame and flies forward.'],
  ['Rocket', 'Satellite', 'easy', 'A rocket launches; a satellite stays in orbit.'],
  ['Ambulance', 'Fire truck', 'easy', 'An ambulance carries patients; a fire truck water and ladders.'],
  ['Taxi', 'Rideshare', 'easy', 'A rideshare is hailed through an app, not the street.'],
  ['Limousine', 'Sedan', 'easy', 'A limousine is stretched with a partition and a driver.'],
  ['SUV', 'Hatchback', 'medium', 'A hatchback is small with a rear door; an SUV tall and heavy.'],
  ['Convertible', 'Coupe', 'medium', 'A convertible has a folding roof.'],
  ['Pickup truck', 'Station wagon', 'medium', 'A pickup has an open bed; a wagon an enclosed extended roof.'],
  ['Tractor', 'Bulldozer', 'easy', 'A bulldozer pushes with a front blade; a tractor pulls implements.'],
  ['Crane', 'Forklift', 'easy', 'A forklift lifts pallets at ground level; a crane hoists high.'],
  ['Excavator', 'Backhoe', 'hard', 'A backhoe is a tractor with a loader in front and a small digger behind.'],
  ['Trailer', 'Caravan', 'medium', 'A caravan is towed accommodation; a trailer carries cargo.'],
  ['Motorhome', 'Caravan', 'medium', 'A motorhome drives itself; a caravan must be towed.'],
  ['Sledge', 'Toboggan', 'medium', 'A toboggan is a long curved board with no runners.'],
  ['Snowmobile', 'Jet ski', 'easy', 'Different surface entirely: snow versus water.'],
  ['Hovercraft', 'Ferry', 'medium', 'A hovercraft rides on a cushion of air over land or water.'],
  ['Cable car', 'Chairlift', 'medium', 'A chairlift is open seating; a cable car an enclosed cabin.'],
  ['Escalator', 'Elevator', 'easy', 'An escalator is a moving staircase; an elevator a vertical box.'],
  ['Wheelbarrow', 'Trolley', 'easy', 'A wheelbarrow has one wheel and is tipped to unload.'],
  ['Rickshaw', 'Tuk-tuk', 'medium', 'A tuk-tuk is motorised; a rickshaw is pulled or pedalled.'],
  ['Carriage', 'Cart', 'medium', 'A carriage is sprung for passengers; a cart carries goods.'],
  ['Segway', 'Hoverboard', 'medium', 'A Segway has a handlebar and self-balances upright.'],
  ['Unicycle', 'Tricycle', 'easy', 'One wheel versus three.'],
  ['Tandem bicycle', 'Bicycle', 'easy', 'A tandem seats two riders in line.'],
  ['Freight train', 'Passenger train', 'easy', 'One carries goods, the other people.'],
  ['Anchor', 'Rudder', 'easy', 'An anchor holds a vessel still; a rudder steers it.'],
  ['Sail', 'Oar', 'easy', 'A sail uses wind; an oar muscle.'],
  ['Runway', 'Taxiway', 'medium', 'Aircraft take off from a runway and merely move along a taxiway.'],
  ['Harbour', 'Marina', 'medium', 'A marina is for small leisure boats; a harbour for shipping too.'],
  ['Highway', 'Roundabout', 'easy', 'A roundabout is a circular junction, not a road.'],
  ['Bridge', 'Tunnel', 'easy', 'A bridge crosses over; a tunnel through.'],
]

export const PLACES: PairSeed[] = [
  ['Lake', 'Pond', 'easy', 'A pond is smaller and shallow enough for light to reach the bottom.'],
  ['River', 'Stream', 'easy', 'A stream is narrow enough to step across.'],
  ['Sea', 'Ocean', 'easy', 'An ocean is far larger; seas are partly enclosed by land.'],
  ['Bay', 'Gulf', 'medium', 'A gulf is larger and more deeply enclosed.'],
  ['Beach', 'Shore', 'easy', 'A shore is any land at the water; a beach specifically sand or shingle.'],
  ['Cliff', 'Hill', 'easy', 'A cliff is a vertical rock face.'],
  ['Mountain', 'Hill', 'easy', 'A mountain is higher and steeper.'],
  ['Valley', 'Canyon', 'easy', 'A canyon is narrow with sheer rock walls.'],
  ['Cave', 'Tunnel', 'easy', 'A tunnel is dug on purpose and goes through.'],
  ['Volcano', 'Geyser', 'easy', 'A geyser erupts hot water, not molten rock.'],
  ['Forest', 'Jungle', 'easy', 'A jungle is dense tropical undergrowth.'],
  ['Woods', 'Grove', 'medium', 'A grove is small and often planted.'],
  ['Meadow', 'Prairie', 'medium', 'A prairie is a vast dry grassland; a meadow small and damp.'],
  ['Desert', 'Dune', 'easy', 'A dune is one hill of sand within a desert.'],
  ['Swamp', 'Marsh', 'medium', 'Swamps have trees; marshes only grasses and reeds.'],
  ['Glacier', 'Iceberg', 'easy', 'An iceberg has broken off and floats.'],
  ['Island', 'Peninsula', 'easy', 'A peninsula stays attached to the mainland.'],
  ['Waterfall', 'Rapids', 'easy', 'Rapids stay in the riverbed; a waterfall drops off it.'],
  ['City', 'Town', 'easy', 'A city is larger and formally chartered.'],
  ['Village', 'Suburb', 'easy', 'A suburb sits at the edge of a city; a village stands alone.'],
  ['Street', 'Alley', 'easy', 'An alley is narrow and runs behind buildings.'],
  ['Square', 'Park', 'easy', 'A square is paved and enclosed by buildings.'],
  ['Garden', 'Park', 'easy', 'A garden is cultivated and usually private.'],
  ['Museum', 'Gallery', 'easy', 'A gallery shows art, often for sale; a museum collects and preserves.'],
  ['Library', 'Bookshop', 'easy', 'A library lends; a bookshop sells.'],
  ['Theatre', 'Cinema', 'easy', 'A cinema screens film; a theatre stages live performance.'],
  ['Stadium', 'Arena', 'medium', 'An arena is smaller, indoor and seats all around.'],
  ['Hotel', 'Hostel', 'easy', 'A hostel has shared dormitories and shared rooms.'],
  ['Motel', 'Inn', 'medium', 'A motel opens onto a car park; an inn is older and serves food.'],
  ['Restaurant', 'Cafe', 'easy', 'A cafe is lighter, cheaper and centred on drinks.'],
  ['Bakery', 'Deli', 'easy', 'A deli sells prepared meats and cheeses.'],
  ['Market', 'Supermarket', 'easy', 'A market is stalls and traders; a supermarket one shop.'],
  ['Mall', 'Arcade', 'medium', 'An arcade is a covered walkway of shops, not an enclosed complex.'],
  ['Pharmacy', 'Clinic', 'easy', 'A clinic treats patients; a pharmacy dispenses medicine.'],
  ['Hospital', 'Clinic', 'easy', 'A hospital admits patients overnight.'],
  ['School', 'University', 'easy', 'A university teaches degrees to adults.'],
  ['Office', 'Studio', 'easy', 'A studio is a workspace for creative or broadcast work.'],
  ['Factory', 'Warehouse', 'easy', 'A factory makes goods; a warehouse only stores them.'],
  ['Farm', 'Ranch', 'medium', 'A ranch raises grazing livestock over open land.'],
  ['Barn', 'Shed', 'easy', 'A barn is large and holds animals or harvest.'],
  ['Castle', 'Palace', 'easy', 'A castle is fortified for defence; a palace built for display.'],
  ['Tower', 'Skyscraper', 'easy', 'A skyscraper is occupied floor upon floor.'],
  ['Church', 'Chapel', 'easy', 'A chapel is small and often inside a larger building.'],
  ['Temple', 'Shrine', 'medium', 'A shrine is a small site around one sacred object or figure.'],
  ['Cemetery', 'Memorial', 'easy', 'A memorial marks remembrance without necessarily holding graves.'],
  ['Zoo', 'Aquarium', 'easy', 'An aquarium holds aquatic animals in tanks.'],
  ['Playground', 'Amusement park', 'easy', 'An amusement park charges entry and runs rides.'],
  ['Campsite', 'Cabin', 'easy', 'A cabin is a built shelter; a campsite a pitch for tents.'],
  ['Lighthouse', 'Watchtower', 'medium', 'A lighthouse warns ships with a light; a watchtower is for observation.'],
  ['Border', 'Coast', 'easy', 'A border divides territories; a coast meets the sea.'],
]

export const SPORTS: PairSeed[] = [
  ['Football', 'Rugby', 'easy', 'Rugby passes backwards and allows no forward throw.'],
  ['Basketball', 'Netball', 'medium', 'Netball has no backboard, no dribbling and fixed positions.'],
  ['Volleyball', 'Badminton', 'easy', 'Badminton uses rackets and a shuttlecock over a higher net.'],
  ['Tennis', 'Squash', 'easy', 'Squash is played against a wall in an enclosed court.'],
  ['Table tennis', 'Tennis', 'easy', 'One is played on a table with paddles.'],
  ['Baseball', 'Cricket', 'easy', 'Cricket has two wickets and batters who need not run.'],
  ['Softball', 'Baseball', 'medium', 'Softball uses a larger ball, underarm pitching and a smaller diamond.'],
  ['Hockey', 'Lacrosse', 'medium', 'Lacrosse carries the ball in a netted stick.'],
  ['Ice hockey', 'Field hockey', 'easy', 'One is on ice with a puck, the other on grass with a ball.'],
  ['Golf', 'Mini golf', 'easy', 'Mini golf is putting only, over obstacles.'],
  ['Boxing', 'Wrestling', 'easy', 'Wrestling grapples and pins; boxing strikes only.'],
  ['Judo', 'Karate', 'medium', 'Judo throws and grapples; karate strikes.'],
  ['Taekwondo', 'Karate', 'medium', 'Taekwondo is Korean and kick-dominant.'],
  ['Fencing', 'Archery', 'easy', 'Archery shoots at a target; fencing duels with blades.'],
  ['Sprint', 'Marathon', 'easy', 'A marathon is endurance over 42 kilometres.'],
  ['Hurdles', 'Steeplechase', 'medium', 'Steeplechase adds a water jump over a longer distance.'],
  ['Long jump', 'Triple jump', 'easy', 'The triple jump adds a hop and a step before the leap.'],
  ['High jump', 'Pole vault', 'easy', 'The pole vault uses a pole to clear a far higher bar.'],
  ['Shot put', 'Discus', 'easy', 'A discus is a flat disc spun and thrown; a shot is pushed.'],
  ['Javelin', 'Hammer throw', 'easy', 'The hammer is a weight on a wire spun in circles.'],
  ['Swimming', 'Diving', 'easy', 'Diving is judged on the entry, not the distance.'],
  ['Water polo', 'Synchronised swimming', 'easy', 'Water polo is a scoring contest with a ball.'],
  ['Surfing', 'Windsurfing', 'easy', 'Windsurfing adds a sail mounted on the board.'],
  ['Rowing', 'Kayaking', 'medium', 'Rowers face backwards with oars in locks; kayakers face forward.'],
  ['Sailing', 'Rowing', 'easy', 'Sailing uses wind, rowing muscle.'],
  ['Skiing', 'Snowboarding', 'easy', 'A snowboard is one board with both feet strapped sideways.'],
  ['Ice skating', 'Roller skating', 'easy', 'Blades on ice versus wheels on ground.'],
  ['Curling', 'Bowling', 'medium', 'Curling slides stones on ice toward a target circle.'],
  ['Bowling', 'Bocce', 'medium', 'Bocce is played on dirt or grass toward a small target ball.'],
  ['Darts', 'Archery', 'easy', 'Darts are thrown by hand at a close board.'],
  ['Snooker', 'Pool', 'medium', 'Snooker uses a bigger table, more balls and a different scoring order.'],
  ['Chess', 'Checkers', 'easy', 'Chess has six different pieces with different moves.'],
  ['Cycling', 'Triathlon', 'easy', 'A triathlon adds swimming and running.'],
  ['Marathon', 'Ultramarathon', 'medium', 'An ultramarathon is any race longer than a marathon.'],
  ['Gymnastics', 'Acrobatics', 'medium', 'Gymnastics is a judged sport on set apparatus.'],
  ['Weightlifting', 'Powerlifting', 'medium', 'Powerlifting contests squat, bench and deadlift; weightlifting two overhead lifts.'],
  ['Yoga', 'Pilates', 'medium', 'Pilates focuses on core strength and controlled repetition.'],
  ['Climbing', 'Bouldering', 'medium', 'Bouldering is short, ropeless and over mats.'],
  ['Hiking', 'Trekking', 'medium', 'Trekking is multi-day and remote.'],
  ['Skateboarding', 'BMX', 'easy', 'BMX is done on a small bicycle.'],
  ['Referee', 'Umpire', 'medium', 'Different sports use the different title; umpires often judge from a fixed position.'],
  ['Coach', 'Captain', 'easy', 'A captain plays; a coach directs from outside.'],
  ['Goalkeeper', 'Defender', 'easy', 'Only the goalkeeper may handle the ball in the area.'],
  ['Penalty', 'Free kick', 'medium', 'A penalty is taken from a fixed spot against the goalkeeper alone.'],
  ['Offside', 'Foul', 'medium', 'Offside is a position violation, not a contact one.'],
  ['Tournament', 'League', 'easy', 'A league plays a full season table; a tournament is knockout or grouped.'],
  ['Medal', 'Trophy', 'easy', 'A medal is worn; a trophy is held or displayed.'],
  ['Stadium', 'Court', 'easy', 'A court is the marked playing surface itself.'],
  ['Marathon runner', 'Sprinter', 'easy', 'Endurance versus explosive short-distance speed.'],
  ['Draw', 'Forfeit', 'medium', 'A forfeit is a loss by withdrawal, not an equal score.'],
]

export const TECHNOLOGY: PairSeed[] = [
  ['Laptop', 'Tablet', 'easy', 'A laptop has an attached keyboard and hinge.'],
  ['Desktop', 'Laptop', 'easy', 'A desktop is not portable and uses separate parts.'],
  ['Monitor', 'Television', 'easy', 'A television has a tuner and is watched from a distance.'],
  ['Keyboard', 'Mouse', 'easy', 'One types, the other points.'],
  ['Trackpad', 'Mouse', 'easy', 'A trackpad is a flat surface built into the device.'],
  ['Printer', 'Scanner', 'easy', 'A scanner reads paper into the computer.'],
  ['Router', 'Modem', 'medium', 'A modem connects to the provider; a router shares that link locally.'],
  ['Wi-Fi', 'Bluetooth', 'easy', 'Bluetooth pairs devices over a few metres, not a network.'],
  ['Cable', 'Adapter', 'easy', 'An adapter converts between connector types.'],
  ['Charger', 'Battery', 'easy', 'A battery stores power; a charger supplies it.'],
  ['USB', 'HDMI', 'easy', 'HDMI carries video and audio to a display.'],
  ['Hard drive', 'Flash drive', 'easy', 'A flash drive is small, portable and plugs into a port.'],
  ['SSD', 'Hard drive', 'medium', 'An SSD has no spinning platter and no moving parts.'],
  ['RAM', 'Storage', 'medium', 'RAM is fast and cleared on shutdown.'],
  ['Processor', 'Graphics card', 'medium', 'A graphics card handles parallel rendering work.'],
  ['Motherboard', 'Circuit board', 'medium', 'A motherboard is the main board every component connects to.'],
  ['Server', 'Database', 'medium', 'A database stores and queries data; a server runs and serves it.'],
  ['Website', 'App', 'easy', 'An app is installed; a website is opened in a browser.'],
  ['Browser', 'Search engine', 'easy', 'A browser displays pages; a search engine finds them.'],
  ['Email', 'Message', 'easy', 'Email is addressed and stored in a mailbox.'],
  ['Password', 'Passcode', 'medium', 'A passcode is short and numeric.'],
  ['Firewall', 'Antivirus', 'medium', 'A firewall filters connections; antivirus scans files.'],
  ['Encryption', 'Compression', 'medium', 'Compression makes data smaller; encryption unreadable.'],
  ['Backup', 'Archive', 'medium', 'An archive stores what is no longer active; a backup duplicates what is.'],
  ['Cloud', 'Local storage', 'easy', 'Cloud storage is held on someone else machines over the network.'],
  ['Download', 'Upload', 'easy', 'Opposite directions of transfer.'],
  ['Bug', 'Glitch', 'medium', 'A bug is a defect in the code; a glitch a brief unexplained fault.'],
  ['Code', 'Script', 'medium', 'A script runs directly without a separate build step.'],
  ['Software', 'Firmware', 'medium', 'Firmware is embedded in the device and rarely changed.'],
  ['Operating system', 'Application', 'easy', 'The operating system runs the applications.'],
  ['File', 'Folder', 'easy', 'A folder contains files.'],
  ['Screenshot', 'Screen recording', 'easy', 'A recording captures motion over time.'],
  ['Camera', 'Webcam', 'easy', 'A webcam is fixed to a computer for live video.'],
  ['Microphone', 'Speaker', 'easy', 'A microphone records; a speaker plays.'],
  ['Headphones', 'Earbuds', 'easy', 'Earbuds sit inside the ear without a headband.'],
  ['Smartwatch', 'Fitness tracker', 'medium', 'A smartwatch runs apps and shows a full screen.'],
  ['Drone', 'Helicopter', 'easy', 'A drone carries no pilot.'],
  ['Robot', 'Machine', 'easy', 'A robot senses and acts on its own.'],
  ['Sensor', 'Switch', 'easy', 'A switch is operated by hand; a sensor detects.'],
  ['Barcode', 'QR code', 'easy', 'A QR code is a square holding far more data.'],
  ['GPS', 'Compass', 'easy', 'A compass only shows direction, with no position or satellites.'],
  ['Projector', 'Monitor', 'easy', 'A projector throws the image onto a surface.'],
  ['Remote control', 'Console controller', 'easy', 'A controller has sticks and triggers for play.'],
  ['Emulator', 'Simulator', 'hard', 'An emulator reproduces the original hardware exactly; a simulator models behaviour.'],
  ['Update', 'Upgrade', 'medium', 'An upgrade moves to a new version or tier; an update patches the current one.'],
  ['Cache', 'Cookie', 'medium', 'A cookie stores small identifying data; a cache stores fetched content.'],
  ['Link', 'Bookmark', 'easy', 'A bookmark is a saved link kept by the browser.'],
  ['Podcast', 'Radio', 'easy', 'A podcast is downloaded on demand rather than broadcast live.'],
  ['Streaming', 'Broadcast', 'medium', 'Streaming is per-viewer and on demand.'],
  ['Algorithm', 'Formula', 'medium', 'An algorithm is a sequence of steps; a formula a single relation.'],
]

export const MUSIC: PairSeed[] = [
  ['Violin', 'Viola', 'medium', 'A viola is slightly larger and tuned a fifth lower.'],
  ['Cello', 'Double bass', 'medium', 'The double bass is much larger and played standing.'],
  ['Guitar', 'Ukulele', 'easy', 'A ukulele is small with four nylon strings.'],
  ['Acoustic guitar', 'Electric guitar', 'easy', 'An electric guitar needs an amplifier to be heard.'],
  ['Banjo', 'Mandolin', 'medium', 'A banjo has a drum-like skin head; a mandolin a rounded wooden body.'],
  ['Harp', 'Lyre', 'medium', 'A lyre is small, handheld and has a yoke and crossbar.'],
  ['Piano', 'Organ', 'easy', 'An organ sustains notes with air and has stops and pedals.'],
  ['Keyboard', 'Piano', 'easy', 'A keyboard is electronic with selectable sounds.'],
  ['Harpsichord', 'Piano', 'medium', 'A harpsichord plucks its strings and cannot vary volume by touch.'],
  ['Accordion', 'Harmonica', 'easy', 'An accordion has a bellows and keys; a harmonica is blown by mouth.'],
  ['Flute', 'Piccolo', 'medium', 'A piccolo is half the length and sounds an octave higher.'],
  ['Clarinet', 'Oboe', 'medium', 'An oboe uses a double reed and has a sharper, thinner tone.'],
  ['Saxophone', 'Clarinet', 'easy', 'A saxophone is brass and conical; a clarinet cylindrical wood.'],
  ['Bassoon', 'Oboe', 'hard', 'A bassoon is far larger and plays the bass range.'],
  ['Trumpet', 'Trombone', 'easy', 'A trombone changes pitch with a slide, not valves.'],
  ['French horn', 'Trumpet', 'medium', 'A french horn is coiled with a flared bell played facing back.'],
  ['Tuba', 'Trombone', 'easy', 'A tuba is the largest and lowest brass instrument.'],
  ['Drum', 'Cymbal', 'easy', 'A cymbal is a metal plate that rings rather than thuds.'],
  ['Snare drum', 'Bass drum', 'easy', 'A snare is small and rattling; a bass drum deep and struck by pedal.'],
  ['Bongos', 'Congas', 'medium', 'Congas are tall floor-standing drums; bongos small and held between the knees.'],
  ['Tambourine', 'Maracas', 'easy', 'Maracas are shaken rattles; a tambourine has jingles on a frame.'],
  ['Xylophone', 'Marimba', 'hard', 'A marimba has wooden bars with resonators and a warmer, lower tone.'],
  ['Triangle', 'Cowbell', 'easy', 'A cowbell is a struck metal cup with a dull clank.'],
  ['Gong', 'Cymbal', 'medium', 'A gong is hung, much larger and hit with a mallet.'],
  ['Choir', 'Chorus', 'medium', 'A chorus is the repeated section of a song as well as a group.'],
  ['Soprano', 'Alto', 'easy', 'Soprano is the higher voice.'],
  ['Tenor', 'Bass', 'easy', 'Bass is the lower voice.'],
  ['Melody', 'Harmony', 'easy', 'Harmony is the notes sounding beneath and around the tune.'],
  ['Rhythm', 'Tempo', 'medium', 'Tempo is how fast; rhythm is the pattern of the notes.'],
  ['Beat', 'Bar', 'medium', 'A bar is a group of beats.'],
  ['Chord', 'Scale', 'easy', 'A chord sounds together; a scale runs in sequence.'],
  ['Note', 'Rest', 'easy', 'A rest is measured silence.'],
  ['Sharp', 'Flat', 'easy', 'Sharp raises a note, flat lowers it.'],
  ['Verse', 'Chorus', 'easy', 'The chorus repeats with the same words each time.'],
  ['Bridge', 'Solo', 'medium', 'A solo features one player; a bridge is a contrasting written section.'],
  ['Lyrics', 'Poem', 'easy', 'Lyrics are written to be sung to music.'],
  ['Album', 'Single', 'easy', 'A single is one release track.'],
  ['Concert', 'Recital', 'medium', 'A recital is small and usually one performer.'],
  ['Orchestra', 'Band', 'easy', 'An orchestra is large, conducted and strings-led.'],
  ['Conductor', 'Composer', 'easy', 'A composer writes the music; a conductor directs its performance.'],
  ['Jazz', 'Blues', 'medium', 'Blues follows a set chord pattern; jazz improvises more freely.'],
  ['Rock', 'Metal', 'easy', 'Metal is heavier, faster and more distorted.'],
  ['Pop', 'Indie', 'medium', 'Indie describes independent release and a rougher production.'],
  ['Rap', 'Spoken word', 'medium', 'Rap is delivered in rhythm over a beat.'],
  ['Opera', 'Musical', 'medium', 'A musical has spoken dialogue between songs.'],
  ['Symphony', 'Concerto', 'medium', 'A concerto features a soloist against the orchestra.'],
  ['Waltz', 'Tango', 'medium', 'A waltz is in three-beat time and sweeping; a tango sharp and in four.'],
  ['Vinyl', 'Cassette', 'easy', 'A cassette is magnetic tape in a plastic shell.'],
  ['Amplifier', 'Speaker', 'medium', 'An amplifier raises the signal; the speaker turns it into sound.'],
  ['Metronome', 'Tuner', 'medium', 'A metronome keeps time; a tuner checks pitch.'],
]
